<?php

use GuzzleHttp\RequestOptions;
use Spatie\Sitemap\Crawler\Profile;

return [

    /*
     * These options will be passed to GuzzleHttp\Client when it is created.
     * For in-depth information on all options see the Guzzle docs:
     *
     * http://docs.guzzlephp.org/en/stable/request-options.html
     */
    'guzzle_options' => [

        /*
         * Whether or not cookies are used in a request.
         */
        RequestOptions::COOKIES => true,

        /*
         * The number of seconds to wait while trying to connect to a server.
         * Use 0 to wait indefinitely.
         */
        RequestOptions::CONNECT_TIMEOUT => 10,

        /*
         * The timeout of the request in seconds. Use 0 to wait indefinitely.
         */
        RequestOptions::TIMEOUT => 10,

        /*
         * Describes the redirect behavior of a request.
         */
        RequestOptions::ALLOW_REDIRECTS => false,
    ],

    /*
     * The sitemap generator can execute JavaScript on each page so it will
     * discover links that are generated by your JS scripts. This feature
     * is powered by headless Chrome.
     */
    'execute_javascript' => false,

    /*
     * The package will make an educated guess as to where Google Chrome is installed.
     * You can also manually pass its location here.
     */
    'chrome_binary_path' => null,

    /*
     * The sitemap generator uses a CrawlProfile implementation to determine
     * which urls should be crawled for the sitemap.
     */
    'crawl_profile' => Profile::class,

    /*
     * Here you can specify the list of urls that should be included in the sitemap.
     * Each url should be an array with the following keys::
     * - url: The url to include
     * - priority: The priority of the url (between 0.0 and 1.0)
     * - change_frequency: How often the page is likely to change
     * - last_modified: The date of last modification of the page (Carbon instance or null)
     */
    'list' => [
        [
            'url' => '/',
            'priority' => 1.0,
            'change_frequency' => 'daily',
            'last_modified' => null,
        ],
        [
            'url' => '/about',
            'priority' => 0.8,
            'change_frequency' => 'monthly',
            'last_modified' => null,
        ],
        [
            'url' => '/timeline',
            'priority' => 0.8,
            'change_frequency' => 'monthly',
            'last_modified' => null,
        ],
        [
            'url' => '/candidates',
            'priority' => 0.9,
            'change_frequency' => 'monthly',
            'last_modified' => null,
        ],
        [
            'url' => '/vote',
            'priority' => 1.0,
            'change_frequency' => 'monthly',
            'last_modified' => null,
        ],
        [
            'url' => '/signin',
            'priority' => 0.7,
            'change_frequency' => 'monthly',
            'last_modified' => null,
        ],
    ],

];
